//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StroiMat.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int OrderID { get; set; }
        public string OrderContainer { get; set; }
        public Nullable<int> OrderUserID { get; set; }
        public int OrderTotal { get; set; }
    
        public virtual User User { get; set; }
    }
}
